### ISSUE TITLE
Pewpew Stargate Carter Addon Pack Bug

### ISSUE THREAD

**Issue by gyuri961012** [MattJeanes/PewPew#34]
Maybe everyone know that the Carter Addon Pack is more realistic with Spacebuild and Pewpew!
With pewpew i can destroy spaceships,..etc.!
But if i put shield from CAP and if i shoot to the ground or walls with CAP weapons the shield energy drain like if i shoot to the shield.
If i remove pewpew then everything is fine.(The pewpew causing this bug)
I think it may be some interference in the source code.
Please Fix this  shield bug. We wanna play CAP with PewPew!
Without pewpew i cant destroy enemies ships and other things.

**Comment by MattJeanes** [comment]
It's caused by attempted compatibility with CAP. I'll remove the compatibility file and all should be good.

**Comment by gyuri961012** [comment]
Thank you for fixing this bug.I will wait for the update.

**Comment by MattJeanes** [comment]
Sorry for the wait, I've been busy with other things. Let me know if this update works. If it does then I'll push the changes to Workshop. Thank you.

**Comment by gyuri961012** [comment]
Works good! Thank you.
You can upload to the workshop.
Thank you!!

**Comment by MattJeanes** [comment]
Alright cool, just pushing update now.
