### ISSUE TITLE
I created an E2 Extension.

### ISSUE THREAD

**Issue by TheMerkyShadow** [MattJeanes/PewPew#37]
I made this extension because it's annoying that wires do not get preserved through duping.
This extension allows player to spawn weapons through e2. Effectively making pewpew turrets and systems. This extension has all of the safety features such as pewpew count and admin/superadmin checks.

http://pastebin.com/7Zqw4K2C

Please consider adding it...

**Comment by MattJeanes** [comment]
Code looks pretty decent, I'll try it out first and merge in if happy

**Comment by TheMerkyShadow** [comment]
Add me on steam if you have any questions or concerns.

**Comment by TheMerkyShadow** [comment]
It's been a few days are you going to add it?

**Comment by MattJeanes** [comment]
Sorry haven't really had any time to check it out. I've got it on my list and I'll get round to it.

**Comment by MattJeanes** [comment]
Okay made some changes to it and put it on a branch:

https://github.com/MattJeanes/PewPew/tree/pewcreate-extension

I'll get Divran to look over before merging it in.
